:PROPERTIES:
:ID:       7EAF6B3D-7FE3-4E48-A0AF-545506962717
:END:
#+title: Nec 2014 110


* Nec 2014 110
** 110.3(B)	Equipment to be installed according to its listing and labeling instructions
** 110.7		Completed wiring shall be free from shorts or ground faults
** 110.8 		Only recognized wiring methods allowed by the code
** 110.9 		Deals with Amps Interrupting Capacity (AIC). The requirement is that all devices that are intended to break fault current (fuses and breakers) are rated for the amount of fault current available at their line side terminals.
** 110.10	 Deals with Short Circuit Current Rating (SCCR) and Withstand Current Rating (WCR). Their requirement is that equipment (i.e. wire and bus bars) be able to carry fault currents until the protective device operates.
** 110.11 No deteriorating agents, paint solvents etc. Equipment designated dry location protected from the weather during construction.
** 110.12	 Installations to be in a neat workman like manner
** 110.12(A)	 Unused openings shall be closed KO seals
** 110.12(B)	 Protection of internal parts from damage, paint, cleansers, etc. Also must be in safe operating condition.
** 110.13(A) 	Equipment to be securely mounted.
** 110.13(B)	Ventilation required around equipment
** 110.14(A) 	Electrical Connections, tight, no dissimilar metals, 1 wire per terminal/Lug
** 110.14(B)	Splices, joints and taps to have equivalent insulation.
** 110.14(C)	Termination degree rating limits conductor ampacity (75 degree)
** 110.15 	Hi-leg orange and marked at each connection
** 110.16 	Electrical equipment, panelboards, MCC?s, meter sockets, etc. other than dwelling units, shall be field marked to warn against arc flashes
** 110.18	Arcing parts protected. No plywood mounting of contactors
** 110.21 	All electrical equipment is to have the manufacturer?s name and other descriptive information.
** 110.22(A) 	Disconnecting means shall be marked unless its purpose is evident.
** 110.24(A)	Service equipment other than dwelling units shall be field marked with the 
- AIC rating. Marking shall be able to withstand the environment
** 110.26A 	Working spaces about electrical equipment
** 110.26D 	Illumination shall be provided for service equipment, switch gear, etc? and not by occupancy sensors.
** 110.28	ENCLOSURE TABLE ? Indoor/Outdoor use

* 
