:PROPERTIES:
:ID:       ACAC14B9-A2E8-4EAC-B2AF-5DB13F92D59A
:END:
#+title: NEC Top 10 Code Articles for Residential


* Article 100 Definitions

* Article 110.3b Installation and Use.
(B) Installation and Use. Listed or labeled equipment shall be installed and used in accordance with any instructions included in the listing or labeling.

* Article 210.8 Ground-Fault Circuit-Interrupter Protection for Personnel.
Ground-fault circuit-interrupter protection for personnel shall be provided as required in 210.8(A) through (E). The ground-fault circuit interrupter shall be installed in a readily accessible location.

(A) Dwelling Units.

(A) Dwelling Units. ampere receptacles installed in the locations specified in 210.8(A)(1) through (10) shall have ground-fault circuitinterrupter protection for personnel.
(1) Bathrooms

(2) Garages, and also accessory buildings that have a floor located at or below grade level not intended as habitable rooms and limited to storage areas, work areas, and areas of similar use

(3) Outdoors
Exception to (3): Receptacles that are not readily accessible and are supplied by a branch circuit dedicated to electric snow-melting, deicing, or pipeline and vessel heating equipment shall be permitted to be instal‐ led in accordance with 426.28 or 427.22, as applicable.

(4) Crawl spaces — at or below grade level

(5) Unfinished portions or areas of the basement not inten‐ ded as habitable rooms
Exception to (5): A receptacle supplying only a permanently installed fire alarm or burglar alarm system shall not be required to have groundfault circuit-interrupter protection.

Informational Note: See 760.41(B) and 760.121(B) for power supply requirements for fire alarm systems.  Receptacles installed under the exception to 210.8(A)(5) shall not be considered as meeting the requirements of 210.52(G).

(6) Kitchens — where the receptacles are installed to serve the countertop surfaces

(7) Sinks — where receptacles are installed within 1.8 m (6 ft) from the top inside edge of the bowl of the sink

(8) Boathouses

(9) Bathtubs or shower stalls — where receptacles are instal‐ led within 1.8 m (6 ft) of the outside edge of the bathtub or shower stall

(10) Laundry areas

(B) Other Than Dwelling Units.
All single-phase receptacles rated 150 volts to ground or less, 50 amperes or less and threephase receptacles rated 150 volts to ground or less, 100 amperes or less installed in the following locations shall have ground-fault circuit-interrupter protection for personnel.

(1) Bathrooms
(2) Kitchens
(3) Rooftops
Exception: Receptacles on rooftops shall not be required to be readily accessible other than from the rooftop.
(4) Outdoors

Exception No. 1 to (3) and (4): Receptacles that are not readily accessi‐ ble and are supplied by a branch circuit dedicated to electric snowmelting, deicing, or pipeline and vessel heating equipment shall be permitted to be installed in accordance with 426.28 or 427.22, as applicable.
Exception No. 2 to (4): In industrial establishments only, where the conditions of maintenance and supervision ensure that only qualified personnel are involved, an assured equipment grounding conductor program as specified in 590.6(B)(3) shall be permitted for only those receptacle outlets used to supply equipment that would create a greater hazard if power is interrupted or having a design that is not compatible with GFCI protection.

(5) Sinks — where receptacles are installed within 1.8 m (6 ft) from the top inside edge of the bowl of the sink  Exception No. 1 to (5): In industrial laboratories, receptacles used to supply equipment where removal of power would introduce a greater hazard shall be permitted to be installed without GFCI protection. Exception No. 2 to (5): For receptacles located in patient bed locations of general care (Category 2) or critical care (Category 1) spaces of health care facilities other than those covered under 210.8(B)(1), GFCI protec‐ tion shall not be required.

(6) Indoor wet locations
(7) Locker rooms with associated showering facilities (8) Garages, service bays, and similar areas other than vehi‐ cle exhibition halls and showrooms
(9) Crawl spaces — at or below grade level
(10) Unfinished portions or areas of the basement not intended as habitable rooms

(C) Boat Hoists. GFCI protection shall be provided for outlets not exceeding 240 volts that supply boat hoists installed in dwelling unit locations.
(D) Kitchen Dishwasher Branch Circuit. GFCI protection shall be provided for outlets that supply dishwashers installed in dwelling unit locations.
N (E) Crawl Space Lighting Outlets. GFCI protection shall be provided for lighting outlets not exceeding 120 volts installed in crawl spaces.

* Article 210.12 Arc-Fault Circuit-Interrupter Protection 
210.12 Arc-Fault Circuit-Interrupter Protection. Arc-fault circuit-interrupter protection shall be provided as required in

210.12(A), (B), and (C). The arc-fault circuit interrupter shall be installed in a readily accessible location.

(A) Dwelling Units.
(A) Dwelling Units. ampere branch circuits supplying outlets or devices installed in dwelling unit kitchens, family rooms, dining rooms, living rooms, parlors, libraries, dens, bedrooms, sunrooms, recreation rooms, closets, hallways, laundry areas, or similar rooms or areas shall be protected by any of the means described in 210.12(A)(1) through (6):

(1) A listed combination-type arc-fault circuit interrupter, installed to provide protection of the entire branch circuit

(2) A listed branch/feeder-type AFCI installed at the origin of the branch-circuit in combination with a listed outlet branch-circuit type arc-fault circuit interrupter installed at the first outlet box on the branch circuit. The first outlet box in the branch circuit shall be marked to indicate that it is the first outlet of the circuit.

(3) A listed supplemental arc protection circuit breaker installed at the origin of the branch circuit in combina‐ tion with a listed outlet branch-circuit type arc-fault circuit interrupter installed at the first outlet box on the branch circuit where all of the following conditions are met: a. The branch-circuit wiring shall be continuous from the branch-circuit overcurrent device to the outlet branch-circuit arc-fault circuit interrupter. b. The maximum length of the branch-circuit wiring from the branch-circuit overcurrent device to the first outlet shall not exceed 15.2 m (50 ft) for a 14 AWG conductor or 21.3 m (70 ft) for a 12 AWG conductor. c. The first outlet box in the branch circuit shall be marked to indicate that it is the first outlet of the circuit.

(4) A listed outlet branch-circuit type arc-fault circuit inter‐ rupter installed at the first outlet on the branch circuit in combination with a listed branch-circuit overcurrent protective device where all of the following conditions are met: a. The branch-circuit wiring shall be continuous from the branch-circuit overcurrent device to the outlet branch-circuit arc-fault circuit interrupter. b. The maximum length of the branch-circuit wiring from the branch-circuit overcurrent device to the first outlet shall not exceed 15.2 m (50 ft) for a 14 AWG conductor or 21.3 m (70 ft) for a 12 AWG conductor. c. The first outlet box in the branch circuit shall be marked to indicate that it is the first outlet of the circuit. d. The combination of the branch-circuit overcurrent device and outlet branch-circuit AFCI shall be identi‐ fied as meeting the requirements for a system combi‐ nation–type AFCI and shall be listed as such.

(5) If RMC, IMC, EMT, Type MC, or steel-armored Type AC cables meeting the requirements of 250.118, metal wire‐ ways, metal auxiliary gutters, and metal outlet and junc‐ tion boxes are installed for the portion of the branch circuit between the branch-circuit overcurrent device and the first outlet, it shall be permitted to install a listed outlet branch-circuit type AFCI at the first outlet to provide protection for the remaining portion of the branch circuit.

(6) Where a listed metal or nonmetallic conduit or tubing or Type MC cable is encased in not less than 50 mm (2 in.) of concrete for the portion of the branch circuit between the branch-circuit overcurrent device and the first outlet, it shall be permitted to install a listed outlet branchcircuit type AFCI at the first outlet to provide protection for the remaining portion of the branch circuit. Exception: Where an individual branch circuit to a fire alarm system installed in accordance with 760.41(B) or 760.121(B) is installed in RMC, IMC, EMT, or steel-sheathed cable, Type AC or Type MC, meet‐ ing the requirements of 250.118, with metal outlet and junction boxes, AFCI protection shall be permitted to be omitted.

Informational Note No. 1: For information on combination-type and branch/feeder-type arc-fault circuit interrupters, see UL 1699-2011, Standard for Arc-Fault Circuit Interrupters. For infor‐ mation on outlet branch-circuit type arc-fault circuit interupters, see UL Subject 1699A, Outline of Investigation for Outlet Branch Circuit Arc-Fault Circuit-Interrupters. For information on system combination AFCIs, see UL Subject 1699C, Outline of Investiga‐ tion for System Combination Arc-Fault Circuit Interrupters.

Informational Note No. 2: See 29.6.3(5) of NFPA 72 -2013, National Fire Alarm and Signaling Code, for information related to secondary power-supply requirements for smoke alarms installed in dwelling units.

Informational Note No. 3: See 760.41(B) and 760.121(B) for power-supply requirements for fire alarm systems.

(B) Dormitory Units.

(B) Dormitory Units. ampere branch circuits supplying outlets and devices installed in dormitory unit bedrooms, living rooms, hallways, closets, bathrooms, and similar rooms shall be protected by any of the means described in 210.12(A)(1) through (6).

N (C) Guest Rooms and Guest Suites. All 120-volt, single-phase, 15- and 20-ampere branch circuits supplying outlets and devi‐ ces installed in guest rooms and guest suites of hotels and motels shall be protected by any of the means described in 210.12(A)(1) through (6).

(D) Branch Circuit Extensions or Modifications — Dwelling Units and Dormitory Units. In any of the areas specified in 210.12(A) or (B), where branch-circuit wiring is modified, replaced, or extended, the branch circuit shall be protected by one of the following:

(1) A listed combination-type AFCI located at the origin of the branch circuit
(2) A listed outlet branch-circuit-type AFCI located at the first receptacle outlet of the existing branch circuit

Exception: AFCI protection shall not be required where the extension of the existing conductors is not more than 1.8 m (6 ft) and does not include any additional outlets or devices.

* Article 210.23 Permissible Loads, Multiple-Outlet Branch Circuits.

210.23 Permissible Loads, Multiple-Outlet Branch Circuits. In no case shall the load exceed the branch-circuit ampere rating. A branch circuit supplying two or more outlets or recep‐ tacles shall supply only the loads specified according to its size as specified in 210.23(A) through (D) and as summarized in 210.24 and Table 210.24.

Table 210.21(B)(2) Maximum Cord-and-Plug-Connected Load to Receptacle

|--------------------------+-----------------------------+------------------------|
| Circuit Rating (Amperes) | Receptacle Rating (Amperes) | Maximum Load (Amperes) |
|                 15 or 20 |                          15 |                     12 |
|                       20 |                          20 |                     16 |
|                       30 |                          30 |                     24 |
|--------------------------+-----------------------------+------------------------|

Table 210.21(B)(3) Receptacle Ratings for Various Size Circuits (A) 15- and 20-Ampere Branch Circuits. A 15- or 20-ampere branch circuit shall be permitted to supply lighting units or other utilization equipment, or a combination of both, and shall comply with 210.23(A)(1) and (A)(2).

Exception: The small-appliance branch circuits, laundry branch circuits, and bathroom branch circuits required in a dwelling unit(s) by 210.11(C)(1), (C)(2), and (C)(3) shall supply only the receptacle outlets specified in that section.

(1) Cord-and-Plug-Connected Equipment Not Fastened in Place. The rating of any one cord-and-plug-connected utiliza‐ tion equipment not fastened in place shall not exceed 80 percent of the branch-circuit ampere rating.

(2) Utilization Equipment Fastened in Place.

The total rating of utilization equipment fastened in place, other than lumin‐ aires, shall not exceed 50 percent of the branch-circuit ampere rating where lighting units, cord-and-plug-connected utilization equipment not fastened in place, or both, are also supplied.

(B) 30-Ampere Branch Circuits. A 30-ampere branch circuit shall be permitted to supply fixed lighting units with heavy-duty lampholders in other than a dwelling unit(s) or utilization equipment in any occupancy. A rating of any one cord-andplug-connected utilization equipment shall not exceed 80 percent of the branch-circuit ampere rating.

(C) 40- and 50-Ampere Branch Circuits. A 40- or 50-ampere branch circuit shall be permitted to supply cooking appliances that are fastened in place in any occupancy. In other than dwelling units, such circuits shall be permitted to supply fixed lighting units with heavy-duty lampholders, infrared heating units, or other utilization equipment.

(D) Branch Circuits Larger Than 50 Amperes. Branch circuits larger than 50 amperes shall supply only nonlighting outlet loads.
