:PROPERTIES:
:ID:       D54DAE1B-9738-43F8-93C6-01A0596F3CBF
:END:
#+title: NEC Quick Code 2014



BCAP (Broward County Administrative Provisions) Chapter 1; 6th Edition
** 101.4.1 	References (gives permission to use) Chapter 27 of the FBC Electrical, NFPA 70, Fire Protection Provisions of this code, and FFPC. May need rewording in Main Doc
** 104.10 Minor changes to plans (pen notations) can be made by plans examiner. 	(Also See 107.3.0.1)
** 104.10 	The Plans Examiner shall fulfill the duties of the Chief in his absence.
** 104.11	 Inspection failure to be in writing and have relevant code section.
** 104.12.2.4 	An application for temporary service shall be made in writing by the electrical contractor, firm, corporation, or owner. And only approved if safe.
** 104.12.2.5 	The Electrical Inspector is hereby empowered to inspect or re**inspect any wiring, equipment? Electrical wiring and equipment must be in good working condition.
** 104.12.2.6 	The electrical inspector has power to disconnect cords, branch circuits?
** 104.25.1 	The BO or representative can order concealed work exposed.
** 104.28 	Right of entry to any at any reasonable time, any building, structure or premises for the purpose of making any inspection or investigation.
** 105.1 		Permits required AND No working without a permit
** 105.3 		Permit Application required.
** 105.3.0.1	Qualification of Applicant Application for permit will be accepted from owner, qualified persons or firms, or authorized agents.
** 105.3.0.1.1 	Qualification of persons or firms shall be qualified by Examining Boards approved by BORA, the State of Florida, Department of Professional Regulation by authority of Chapter 489.113(3).
** 105.3.0.2 	Permit apps shall be accompanied by plans/specifications as required.
** 105.3.1 	If the application or construction documents (plans) don?t not conform to codes, the B.O. or Fire Official shall site relevant code sections.
** 105.3.1.4.5 	The Installation, Alteration, or Repair of any electrical wiring or equipment requires a permit. (excludes some low voltage alarms) NOTE: Maintenance does not require a permit.
** 105.4 		Issuance of a permit does not allow errors or violations even if a plan is approved.
** 105.6.2 	Work must match plans.
** 105.6.4 	Allows a change of contractor.
** 105.7 		Permit Card must be placed on the front of premises available on demand?
** 107.2.1 	Construction documents shall be of sufficient clarity to indicate the location, nature and extent of the work proposed. 
** 107.3 		All plans shall be reviewed by a BORA Certified Plans Examiner.
BCAP (Broward County Administrative Provisions) Chapter 1; 6th Edition

** 107.3.0.1 	Minor corrections may be corrected by notation on the prints with the approval of the designer.
** 107.3.4.0.1 	Alterations, Repairs, Improvements, Replacements, OR Additions to Buildings and Structures (except SFR) $15,000 or more require a professional designer.
** 107.3.4.0.3 	Alterations, Repairs, Improvements, Replacements, AND Additions to SFR $30,000 or more require a professional designer. May need rewording in Main Doc
** 107.3.4.0.5 	It is at the discretion of the Building Official to decide if plans that are predominately Mech or Elec in nature require professional design.
** 107.3.5(B)1**18 Minimum plan review criteria for buildings.
** 107.3.5(G) 	Minimum plan review criteria for Residential (1 & 2 Fam). Electrical plans shall be drawn at ¬? = 1? for buildings less than 5000sq?. 
** 107.3.5.3 	Any specifications in which general expressions are used to the effect that ?work shall be done in accordance with the Building Code? or ?to the satisfaction of the Building Official? shall be deemed imperfect and incomplete, and every reference to this Code shall be by section or sub**section number applicable to the materials to be used, or to the methods of construction proposed.
** 108.3 		Temporary Power ? gives BO/Chief authority to release power before final.
** 109.3.1 	The Building Official may require an estimate of the cost utilizing RSMeans, copies of signed contract
** 109.4 		Any person who commences any work for which a permit is required before obtaining permission fined a penalty of 100 percent of the usual permit fee in addition to the required permit fees.
** 110.1 		The permit holder is responsible to make work accessible and exposed. No Access for inspection.
** 110.1.3 	Sanitary facilities are required on job for inspections.
** 110.1.7 	Ladders, material, power, coordination for access and labor, necessary for inspection and/or test shall be supplied by the permit holder.
** 110.3(B)1**10 Required Electrical inspections.
** 110.5 		Contractor responsible to call in inspections
** 110.9.1 	Work incomplete; Contractor should check work; (not ready for inspection).
** 110.15 	40**year inspection of buildings by BORA guidelines
** 112.1 		No person shall make connections from a utility source until released by the Building Official or Chief Electrical Inspector
** 112.2 		Temp power for use ? 

BCAP (Broward County Administrative Provisions) Chapter 1; 6th Edition

** 112.2.1 	Energizing Systems It shall be unlawful to energize any wiring system or portion thereof until the electrical work has been inspected.
** 112.3 		Authority to disconnect service utilities The Building Official or Chief Electrical Inspector shall have the authority to authorize disconnection of utility service.
** 115.1 		Stop Work Order Whenever the Building Official finds any work being performed in a dangerous or unsafe manner, the Building Official is authorized to issue a stop work order.
** 118.1.3 	TWO**WAY RADIO COMMUNICATION ENHANCED PUBLIC SAFETY SIGNAL BOOSTER SYSTEMS (BDA) ** The AHJ shall determine if a new building or existing building shall require that a two**way radio communication enhanced public safety signal booster system be installed
** 118.1.4 	(BDA) For new buildings a CO shall not be issued until proven that is in compliance. It should be determined before Building is Designed.
** 118.2.1(8) 	(BDA) Documentation ? Plans shall show that the BDA enclosure shall be painted red with 2? high contrasting letters. Include the following information: a) Fire Department Signal Booster b) Permit Number: ________ c) Serviced by: Vendor name and telephone



Residential Energy Conservation Code 2017

** R402.4.5 	Recessed Lighting shall be IC rated and sealed with a gasket or caulk
** 



Commercial Energy Conservation Code 2017

** C402.5.8 	Recessed Lighting shall be IC rated and sealed with a gasket or caulk
** C405.2.1 	Occupancy Sensors shall be installed in CLASS/LECTURE/TRAINING RMS, CONFERENCE/MEETING/MULTIPURPOSE RMS COPY/PRINT RMS, LOUNGES, LUNCH/BREAK RM, PRIVATE OFFICES, RESTROOMS, STORAGE RM, JANITORIAL CLOSET, LOCKER RMS, other spaces 300 sq? or less. The exception is if sensors would pose a hazard. 
** C405.2.5 	Exterior Lighting Controls ? 
o Shall be controlled automatically to turn off with available daylight.
o The lighting shall have controls to reduce the lighting power by >30%
o All time switches shall be able to retain programming for 10hrs with power loss
** C405.6.1	Electrical Power Distribution Systems (receptacles) are required that 50% of all 125v 15a & 20a be automatically controlled, permanently marked (see symbol), and evenly distributed in:
o Private offices
o Conference rooms
o Rooms used for printing and/or copying
o Break rooms
o Class rooms
o Individual workstations
o Modular partitions
Does not apply to receptacles designated to equip for continuous operation or safety. Also plug in switching devices are not allowed. 
Automatic Control method can be:
1. Time**of**Day Device:
** Independent schedules shall not exceed 5000sq. ft. areas
** Control schedules shall not control more than 1 floor
** Occupants must be able to override for up to 2 Hrs
2. Occupancy Sensor ? shall turn off receptacles within 20mins of occupants leaving
3. Signal from another control or alarm system that will turn off within 20mins
 
** C405.6.2 	Electrical Metering ? Individual dwelling units must be metered.
** C405.6.3 	Voltage Drop ? The conductors for feeders AND branch circuits combined shall be sized for a max voltage drop of 5%.
** C405.8	Electric Motors shall meet minimum efficiency requirements per Table.
** C405.9.2 	Escalators and moving walks shall have automatic controls to reduce speed when not conveying passengers.



FBC 2017 Building

** FBC 109.3	The Building Official may require an estimate of the cost utilizing RSMeans, copies of signed contract
** FBC 454.1.10.1	POOL REPAIR	Equivalent replacement of equipment is NOT considered a repair or alteration. 
** FBC 454.1.10.3	POOL IONIZER	Installation of a pool Ionizer shall not be considered a repair or alteration, as long as it doesn?t interfere with flow rate.
** FBC 454.2.16 	POOL Outlets supplying pool pump motors, other electrical equipment, and underwater luminaries 120v ? 240v (15a or 20a) shall be GFCI
** AMENDMENT 454.2.16.1 When artificial underwater lighting is utilized in any private swimming or recreational bathing pools, all portions of the pool, including the entire bottom and any and all drains, shall be readily seen without glare. 
There has not been an amendment for the 2017 Code as of 2**6**18
** AMENDMENT 454.2.16.2 When underwater light fixtures are installed for swimming or bathing pools, these fixtures shall not exceed the following maximum output/ performance standards.
          1) 15 volts (RMS) for sinusoidal alternating current 
          2) 21.2 volts peak for nonsinusoidal alternating current 
          3) 30 volts? continuous direct current 
          4) 12.4 volts peak for direct current that is interrupted at a rate of 10 to 200 Hertz 
          5) The maximum incandescent lamp size shall be 300 Watts
There has not been an amendment for the 2017 Code as of 2**6**18
** FBC 907.2.11.5 Where more than one smoke alarm is required to be installed within an individual dwelling IN GROUP ?R? OR ?I**1? occupancy?s, the alarms shall be interconnected. This can be hard**wired or by a listed wireless alarms.


FBC 2017 Building
** FBC 907.2.11.3 Smoke Alarms Near Cooking Appliances ? 
o Ionization Smoke Alarms shall not be placed within 20? of cooking appliances
o Ionization Smoke Alarms with a silencing switch shall not be placed within 10? of cooking appliances
o Photoelectric Smoke Alarms shall not be placed within 6? of cooking appliances
F.Y.I. Group I**1 description in FBC 308.2 (Boarding Houses, Halfway Houses, Convalescent?)
** FBC 907.2.11.6 Power Source in NEW CONSTRUCTION, smoke alarms shall receive their primary power from the building wiring. WIRES SHALL BE PERMANENT.
** 1008.1, 1008.2, 1008.3, 2702.2.11      	Means of Egress Illumination ? illumination shall be provided in the MoE established by Fire Dept, at all times that occupied unless it?s an R**Group. The power for the MoE shall normally come from building power.
** FBC 1008.3.3 MEANS OF EGRESS ILLUMINATION in the event of a power failure an emergency system shall automatically illuminate:
o Electric equipment rooms
o Fire command centers
o Fire pump rooms
o Generator rooms
o Public restrooms >300 sq ft 
** FBC 1008.3.4 The emergency power system shall consist of batteries, unit equipment, or an onsite generator.
** FBC 1010.1.9.9(3)	Mag Lock (electromagntically) locked egress doors; operation of the \\dware must directly interrupt the power to the electromagnetic lock. \\
** FBC 1010.1.10	Electrical rooms with equipment rated >1200amps and >6? wide shall contain panic hardware. And doors shall swing out to exit.
** FBC 1023.5	Penetrations into or through interior exit stairways and ramps are prohibited except for equipment and ductwork necessary for independent ventilation or pressurization, sprinkler piping, standpipes, electrical raceway for fire department communication systems and electrical race**way serving the interior exit stairway and ramp and terminating at a steel box not exceeding 16 square inches (0.010 m2). Such penetrations shall be protected in accordance with Section 714. There shall not be penetrations or communication openings, whether protected or not, between adjacent interior exit stairways and ramps.
** 1522.2	All rooftop equipment shall be mounted to the structure no sleepers.
** FBC 1522.3.4 Electrical conduit shall be lifted off the roof a minimum of 8?
** FBC 2704.1 	Requires metal framing members to be bonded to the EGC (mostly applied to wood frame with metal boxes)
** FBC 107.1 Spec sheets are needed if requested.






FBC 2014 Residential

** R314.1 Smoke detection and notification. 
All smoke alarms shall be listed and labeled in accordance with UL 217 and installed in accordance with the provisions of this code and the household fire warning equipment provisions of NFPA 72. 
** R314.3 Location. Smoke alarms shall be installed in the following locations:
1. In each sleeping room
2. Outside each sleeping area in the immediate vicinity of the bedroom
3. On each additional story of the dwelling & habitable attics.
** R314.3.1 Alterations, repairs and additions. 
When alterations, repairs or additions requiring a permit occur, or when one or more sleeping rooms are added or created in existing dwellings, the individual dwelling unit shall be equipped with smoke alarms located as required for new dwellings.  
Exceptions: 

1. Work involving the exterior surfaces of dwellings, such as the replacement of roofing or siding, or the addition or replacement of windows or doors, or the addition of a porch or deck, are exempt from the requirements of this section. 

2. Installation, alteration or repairs of plumbing or mechanical systems are exempt from the requirements of this section.
** R314.4 Power source. 
Smoke alarms shall receive their primary power from the building wiring when such wiring is served from a commercial source, and when primary power is interrupted, shall receive power from a battery. Wiring shall be permanent and without a disconnecting switch other than those required for overcurrent protection. 

Exceptions: 

1. Smoke alarms shall be permitted to be battery operated when installed in buildings without commercial power. 

2. Hard wiring of smoke alarms in existing areas shall not be required where the alterations or repairs do not result in the removal of interior wall or ceiling finishes exposing the structure, unless there is an attic, crawl space or basement available which could provide access for hard wiring without the removal of interior finishes. 

3. One**family and two**family dwellings and townhomes undergoing a repair, or a Level 1 alteration as defined in the Florida Building Code, may use smoke alarms powered by 10**year nonremovable, nonreplaceable batteries in lieu of retrofitting such dwelling with smoke alarms powered by the dwelling?s electrical system.
** R315.1 Carbon monoxide protection. Every separate building or addition to a building that has a garage or (gas appliances)?shall have a C/O detector with**in 10?
** E4206.4.2.3 When underwater light fixtures are installed for swimming or bathing pools, these fixtures shall not exceed the following maximum output/ performance standards:
     1. 15 volts (RMS) for sinusoidal alternating current
     2. 21.2 volts peak for nonsinusoidal alternating current
     3. 30 volts? continuous direct current
     4. 12.4 volts peak for direct current that is interrupted at a rate of 10 to 200 Hertz
     5. The maximum incandescent lamp size shall be 300 watts
     


NFPA 

HOOD SYSTEM
NFPA 17 for dry chemical and NFPA 17A for wet chemical, but they both read the same:
2**4.3 Shutoff Devices.
2**4.3.1 Upon activation of any cooking equipment fire extinguishing
system, all sources of fuel and power to all equipment
protected by the system shall be shut down.
Gas appliances not requiring protection but located under
the same ventilation equipment shall also be shut off.

NFPA 101
4.6.10 Construction, Repair, and Improvement Operations.
4.6.10.1** Buildings, or portions of buildings, shall be permitted to be occupied during construction, repair, alterations, or additions only where required means of egress and required fire protection features are in place and continuously maintained for the portion occupied or where alternative life safety measures acceptable to the authority having jurisdiction are in place.

4.6.10.2** In buildings under construction, adequate escape facilities shall be maintained at all times for the use of construction workers. Escape facilities shall consist of doors, walk**ways, stairs, ramps, fire escapes, ladders, or other approved means or devices arranged in accordance with the general principles of the Code insofar as they can reasonably be applied to buildings under construction.



1989 Schirmer Tenant Handbook

1. Plans must be sealed ? all plans submitted for the Mall must bear the seal of a Registered Professional Engineer holding a current valid registration in the State of Florida, in the applicable field of engineering. 




Florida Statutes

F.S. 489.113(3).?A contractor shall subcontract all electrical, mechanical, plumbing, roofing, sheet metal, swimming pool, and air**conditioning work, unless such contractor holds a state certificate or registration in the respective trade category, however:
F.S. 553.79(1)(A) requirement to state code section for rejected plan.
Page | 21


