:PROPERTIES:
:ID:       0432C492-1D60-460B-AD3E-92CABF2AB5CD
:END:
#+title: King James Bible


- Genesis 1:3
And God said, Let there be light: and there was light.

[[id:910C6046-A38C-4A29-943A-1DE1D731C5B3][King James Bible False Teachers]]

*Dispensation*
the divine ordering of the affairs of the world. an appointment, arrangement, or favor, as by God. a divinely appointed order or age: the old Mosaic, or Jewish, dispensation; the new gospel, or Christian, dispensation.

Clarence-Larkins Charts

2 Timothy 2:15
15 Study to shew thyself approved unto God, a workman that needeth not to be ashamed, *rightly dividing the word of truth.*

*Creation*
(Genesis 1:3)
Genesis 2:16-17 ::Works:: dont eat the fruit
16 And the LORD God commanded the man, saying, Of every tree of the garden thou mayest freely eat:
17 But of the tree of the knowledge of good and evil, thou shalt not eat of it: for in the day that thou eatest thereof thou shalt surely die.

*Conscience* 
(Genesis 4:50, Job)
Romans 2:13-15
13 For not the hearers of the law are just before God, but the doers of the law shall be justified.
14 For when the Gentiles, which have not the law, do by nature the things contained in the law, these, having not the law, are a law unto themselves:
15 Which shew the work of the law written in their hearts, their conscience also bearing witness, and their thoughts the mean while accusing or else excusing one another;
Genesis 6:5, 8-9

::Faith and Works under Conscience::

5 And GOD saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually.
8 But Noah found grace in the eyes of the LORD.
9 These are the generations of Noah: Noah was a just man and perfect in his generations, and Noah walked with God.

James 2:21-24
21 Was not Abraham our father justified by works, when he had offered Isaac his son upon the altar?
22 Seest thou how faith wrought with his works, and by works was faith made perfect?
23 And the scripture was fulfilled which saith, Abraham believed God, and it was imputed unto him for righteousness: and he was called the Friend of God.
24 Ye see then how that by works a man is justified, and not by faith only.

Genesis 17:7-8
7 And I will establish my covenant between me and thee and thy seed after thee in their generations for an everlasting covenant, to be a God unto thee, and to thy seed after thee.
8 And I will give unto thee, and to thy seed after thee, the land wherein thou art a stranger, all the land of Canaan, for an everlasting possession; and I will be their God. (Physical Jews)

Judges 2:1
1 And an angel of the LORD came up from Gilgal to Bochim, and said, I made you to go up out of Egypt, and have brought you unto the land which I sware unto your fathers; and I said, I will never break my covenant with you.
14:03





Heresies
Replacement Thelogy - They believe they replaced the nation of Israel - Not true because the God's covenent is forever - Genesis 17:7-8
