# FROM golang:1.12.1-alpine3.9 as builder
FROM golang:1.18.1-alpine3.15 as builder

# installing git
RUN apk update && apk upgrade && \
    apk add --no-cache git

RUN mkdir /work
WORKDIR /work
RUN cd /work
RUN go mod init M

RUN go get -u github.com/sirupsen/logrus
RUN go get -u github.com/buaazp/fasthttprouter
RUN go get -u github.com/valyala/fasthttp
RUN echo done